# Generated by Django 5.0.4 on 2024-04-23 09:52

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Pavadinimas')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Trumpas aprašymas')),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Turinys')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Paveikslėlis')),
            ],
            options={
                'verbose_name': 'Programavimo kalbos',
                'verbose_name_plural': 'Programavimo kalbos',
            },
        ),
        migrations.CreateModel(
            name='Django',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Pavadinimas')),
                ('content_dj', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Turinys')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Paveikslėlis')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.category', verbose_name='Kategorija')),
            ],
            options={
                'verbose_name': 'Django',
                'verbose_name_plural': 'Django',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Python',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Pavadinimas')),
                ('content_py', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Turinys')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Paveikslėlis')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.category', verbose_name='Kategorija')),
            ],
            options={
                'verbose_name': 'Python',
                'verbose_name_plural': 'Python',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Pavadinimas')),
                ('question', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Užduotis')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Paveikslėlis')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.category', verbose_name='Kategorija')),
            ],
            options={
                'verbose_name': 'Užduotis',
                'verbose_name_plural': 'Užduotys',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100, verbose_name='Variantas')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Teisingas')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.task', verbose_name='Atsakymas')),
            ],
            options={
                'verbose_name': 'Atsakymas',
                'verbose_name_plural': 'Atsakymai',
            },
        ),
    ]
