# Generated by Django 5.0.6 on 2024-05-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_cplius'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cplius',
        ),
    ]
