# Generated by Django 5.0.6 on 2024-05-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_rename_content_dj_django_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='qtype',
            field=models.CharField(choices=[('TXT', 'Tekstas'), ('RADIO', 'Vienas pasirinkimas'), ('CHECKBOX', 'Daug pasirinkimų')], default='RADIO', max_length=10, verbose_name='Tipas'),
        ),
    ]
