# Generated by Django 5.0.4 on 2024-04-24 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=200, verbose_name='Klientas')),
                ('license_plate', models.CharField(max_length=20, verbose_name='Valstybinis numeris')),
                ('VIN_code', models.CharField(max_length=20, verbose_name='VIN kodas')),
                ('year', models.IntegerField(verbose_name='Metai')),
                ('brand', models.CharField(max_length=200, verbose_name='Markė')),
                ('model', models.CharField(max_length=200, verbose_name='Modelis')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Paveikslėlis')),
            ],
            options={
                'verbose_name_plural': 'Automobiliai',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Paslauga')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kaina')),
            ],
            options={
                'verbose_name_plural': 'Paslaugos',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bendra suma')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.car', verbose_name='Automobilis')),
            ],
            options={
                'verbose_name_plural': 'Užsakymai',
            },
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Kiekis')),
                ('status', models.CharField(blank=True, choices=[('v', 'Vykdoma'), ('b', 'Baigta'), ('e', 'Eilėje')], default='e', max_length=1, null=True, verbose_name='Statusas')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.order', verbose_name='Užsakymas')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autoservice.service', verbose_name='Užsakoma paslauga')),
            ],
            options={
                'verbose_name_plural': 'Užsakytos paslaugos',
                'ordering': ['status'],
            },
        ),
    ]
